name: Update Submodule Rev

on:
  repository_dispatch:
    types:
      - update_backend_rev
      - update_frontend_rev

permissions:
  contents: write

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent repo without submodules
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Override SSH URLs with HTTPS for submodules
        run: |
          git config --file .gitmodules --get-regexp url | while read key url; do
            new_url=$(echo $url | sed 's/git@github.com:/https:\/\/github.com\//')
            git config --file .gitmodules $key $new_url
          done
          git submodule sync
          git submodule update --init --recursive

      - name: Set Git identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Determine submodule and commit to update
        id: submodule-info
        run: |
          if [ "${{ github.event.action }}" = "update_backend_rev" ]; then
            echo "name=andy.grails.backend" >> $GITHUB_OUTPUT
            echo "rev=${{ github.event.client_payload.brev }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.action }}" = "update_frontend_rev" ]; then
            echo "name=andy.grails.frontend" >> $GITHUB_OUTPUT
            echo "rev=${{ github.event.client_payload.frev }}" >> $GITHUB_OUTPUT
          else
            echo "Unknown event type: ${{ github.event.action }}"
            exit 1
          fi

      - name: Update submodule to specific commit
        run: |
          cd ${{ steps.submodule-info.outputs.name }}
          git fetch origin
          git checkout ${{ steps.submodule-info.outputs.rev }}
          cd ..

      - name: Commit updated submodule reference
        id: maybe_commit
        run: |
          git add ${{ steps.submodule-info.outputs.name }}
          if git diff --cached --quiet; then
            echo "No submodule changes to commit."
            echo "committed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Update submodule reference for ${{ steps.submodule-info.outputs.name }}"
            echo "committed=true" >> $GITHUB_OUTPUT
          fi

      - name: Push changes using GitHub Token
        if: steps.maybe_commit.outputs.committed == 'true'
        run: |
          git push https://github.com/${{ github.repository }}.git HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print success message
        run: echo "Submodule ${{ steps.submodule-info.outputs.name }} updated successfully!"
